#!/usr/bin/env bash
# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
#
# Render the Helm chart into deploy/kubernetes/zyntra.yaml for clusters
# without Helm. Credentials come from a Secret you create (zyntra-auth), so
# nothing random is baked into the committed manifest.
set -euo pipefail
cd "$(dirname "$0")/.."

cat <<'EOF'
# Copyright 2026 Zyvor AI Labs · https://zyvor.dev
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
#
# Generated by scripts/render-k8s.sh from deploy/helm/zyntra; do not edit.
#
#   kubectl create namespace zyntra
#   kubectl -n zyntra create secret generic zyntra-auth \
#     --from-literal=ZYNTRA_API_KEY=$(openssl rand -hex 24) \
#     --from-literal=ZYNTRA_SESSION_SECRET=$(openssl rand -hex 32) \
#     --from-literal=ZYNTRA_INGEST_TOKEN=$(openssl rand -hex 24) \
#     --from-literal=ZYNTRA_EXEC_TOKEN=$(openssl rand -hex 24) \
#     --from-literal=ZYNTRA_ADMIN_PASSWORD='choose-one'     # else admin / Admin@321
#   kubectl -n zyntra apply -f deploy/kubernetes/zyntra.yaml
#
# Serves packs/shop in dry-run. Change the -f argument to pick another pack.
EOF
helm template zyntra deploy/helm/zyntra --namespace zyntra \
  --set auth.existingSecret=zyntra-auth \
  | sed -e '/^# Source:/d' -e '/helm.sh\/chart:/d' -e '/app.kubernetes.io\/managed-by:/d' -e '/^[[:space:]]*$/d'
